#!/bin/bash
APP=${!#}

# The parameter $1 is the backup directory location dedicated to the app
# which will be compressed afterward
backup_dir=$1


domain=$(sudo yunohost app setting $APP domain)
path=$(sudo yunohost app setting $APP path)

# Copy the app files
final_path=/var/www/$APP
sudo mkdir -p ${backup_dir}/var/www
sudo cp -a $final_path "${backup_dir}/sources"

# Copy the conf files
sudo cp -a /etc/php5/fpm/pool.d/$APP.conf $backup_dir/php-fpm.conf
sudo cp -a /etc/nginx/conf.d/$domain.d/$APP.conf $backup_dir/nginx.conf

# Backup db
db_pwd=$(sudo yunohost app setting $APP mysqlpwd)
sudo su -c "mysqldump -u $APP -p"$db_pwd" --no-create-db $APP > ${backup_dir}/dump.sql"
